[package]
name = "zoog"
version = "0.3.0-develop"
authors = ["Francis Russell <francis@unchartedbackwaters.co.uk>"]
edition = "2018"
homepage = "https://github.com/FrancisRussell/zoog"
readme = "README.md"
repository = "https://github.com/FrancisRussell/zoog.git"
license = "BSD-3-Clause"
keywords = ["opus", "normalization"]
description = "Modifies Opus output gain values and R128 tags"

[dependencies]
audiopus_sys = { version = "0.2.2", features = ["static"] }
bs1770 = "1.0.0"
byteorder = "1.3.4"
derivative = "2.1.1"
ogg = "0.7.1"
opus = "0.3.0"
tempfile = "3.1.0"
thiserror = "1.0.23"
wild = "2.1.0"

[dependencies.clap]
version = "4.0.10"
default-features = false
features = [ "std", "wrap_help", "derive" ]

[dev-dependencies.rand]
version = "0.8.0"
features = [ "small_rng" ]

[profile.release]
lto = "thin"
strip = "debuginfo"
