fn_params_layout = "Compressed"
fn_single_line = true
force_multiline_blocks = false
group_imports = "StdExternalCrate"
imports_granularity = "Module"
max_width = 120
newline_style = "Unix"
reorder_impl_items = true
use_small_heuristics = "Max"
wrap_comments = true
