on: [push]

name: CI

env:
  CMAKE_POLICY_VERSION_MINIMUM: 3.5

jobs:
  check-build:
    name: Check build
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl]
        platform: [ubuntu-latest]
        include:
          - target: x86_64-apple-darwin
            platform: macos-latest
          - target: aarch64-apple-darwin
            platform: macos-latest
          - target: aarch64-unknown-linux-musl
            platform: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            platform: windows-latest
          - target: i686-pc-windows-msvc
            platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - uses: FrancisRussell/ferrous-actions@v1
        name: Cargo Cache
        with:
          command: cache
      - uses: FrancisRussell/ferrous-actions@v1
        name: Install Rustup
        with:
          command: install-rustup
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          default: true
      - name: Set up Linux musl target
        if: runner.os == 'Linux'
        uses: ./.github/actions/setup-linux-musl-target
        with:
          target: ${{ matrix.target }}
      - uses: FrancisRussell/ferrous-actions@v1
        name: Cargo build
        with:
          command: cargo build
          args: --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v6
        with:
          name: zoog-debug-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/debug/opusgain
            target/${{ matrix.target }}/debug/opusgain.exe
            target/${{ matrix.target }}/debug/zoogcomment
            target/${{ matrix.target }}/debug/zoogcomment.exe
          if-no-files-found: error

  cargo-test:
    name: Cargo test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - name: Install test dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y --no-install-recommends ffmpeg opus-tools vorbis-tools
      - name: Install test dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install ffmpeg opus-tools vorbis-tools
      - name: Install test dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install ffmpeg opus-tools --yes --no-progress
      - uses: FrancisRussell/ferrous-actions@v1
        name: Cargo cache
        with:
          command: cache
      - uses: FrancisRussell/ferrous-actions@v1
        name: Install Rustup
        with:
          command: install-rustup
          toolchain: nightly
          profile: minimal
          default: true
      - uses: FrancisRussell/ferrous-actions@v1
        name: Build library without cli feature
        with:
          command: cargo build
          args: --lib --no-default-features --features audiopus_sys/static
      - uses: FrancisRussell/ferrous-actions@v1
        name: Run tests
        with:
          command: cargo test
          args: --features integration-tests

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: FrancisRussell/ferrous-actions@v1
        name: Cargo cache
        with:
          command: cache
      - uses: FrancisRussell/ferrous-actions@v1
        name: Install Rustup
        with:
            command: install-rustup
            toolchain: nightly
            components: clippy
            default: true
      - uses: FrancisRussell/ferrous-actions@v1
        name: Clippy
        with:
          command: cargo clippy

  check-licenses:
    name: Check licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: FrancisRussell/ferrous-actions@v1
        name: Cargo cache
        with:
          command: cache
      - uses: FrancisRussell/ferrous-actions@v1
        name: Install Rustup
        with:
          command: install-rustup
          toolchain: stable
          profile: minimal
          default: true
      - uses: FrancisRussell/ferrous-actions@v1
        name: Install cargo-about
        with:
          command: cargo install
          args: cargo-about --locked --features cli
      - name: Check third-party licenses
        run: cargo about generate -c ./.about/config.toml ./.about/template.hbs
