on: [push]

name: CI

jobs:
  check-build:
    name: Check build
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu, i686-pc-windows-gnu]
        platform: [ubuntu-latest]
        include:
          - target: x86_64-apple-darwin
            platform: macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.1
        name: Cargo Cache
        with:
          command: cache
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.1
        name: Install Rustup
        with:
          command: install-rustup
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          default: true
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.1
        name: Install cross
        with:
          command: cargo install
          args: cross --git https://github.com/cross-rs/cross --rev 085092ca01d6ac9f5a0b612d9e68bcdf1e50f7ee
      - name: Report Cross version
        run: cross --version
      - name: Report Rustc version
        run: rustc --version
      - name: Build using cross normally
        run: cross build --target=${{ matrix.target }}
