name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CMAKE_POLICY_VERSION_MINIMUM: 3.5

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build binaries
    needs: create-release
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu, i686-pc-windows-gnu]
        platform: [ubuntu-latest]
        include:
          - target: x86_64-apple-darwin
            platform: macos-latest
          - target: aarch64-apple-darwin
            platform: macos-latest
          - target: x86_64-unknown-linux-musl
            apt_packages: musl-dev
          - target: x86_64-pc-windows-gnu
            apt_packages: gcc-mingw-w64-x86-64-posix
          - target: i686-pc-windows-gnu
            apt_packages: gcc-mingw-w64-i686-posix
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - name: Install apt packages
        if: ${{ matrix.apt_packages != '' }}
        run: sudo apt-get install -y --no-install-recommends ${{ matrix.apt_packages }}
      - uses: FrancisRussell/ferrous-actions@v1
        name: Install Rustup
        with:
          command: install-rustup
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          default: true
      - uses: FrancisRussell/ferrous-actions@v1
        name: Build
        with:
          command: cargo build
          args: --release --target=${{ matrix.target }}
      - uses: FrancisRussell/ferrous-actions@v1
        name: Install cargo-about
        with:
          command: cargo install
          args: cargo-about --locked --features cli
      - name: Generate third-party licenses
        run: cargo about generate -c ./.about/config.toml -o THIRD_PARTY_LICENSES.txt ./.about/template.hbs
      - name: Build Archive
        run: ./scripts/build-release ${{ github.ref }} ${{ matrix.target }}
        id: build_archive
      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build_archive.outputs.path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
